<?php

declare(strict_types=1);

namespace Elgg\Tests\RenderSmoke;

use Elgg\IntegrationTestCase;

/**
 * RENDER-SMOKE — every route THIS plugin registers must answer an HTTP
 * status < 500 (no 5xx / PHP fatal), both anonymous AND authenticated.
 *
 * Why this layer exists:
 *   The plugin's unit tests assert entity CRUD and view existence in the
 *   CLI SAPI. They keep passing even while the route -> resource -> view
 *   render path fatals under the web SAPI. This test exercises that exact
 *   path by issuing real HTTP GETs against the running stack, so a
 *   render-layer regression fails a TEST instead of being discovered by
 *   reactive crawling after the fact.
 *
 * Scope:
 *   Only the plugin's OWN routes, read from its elgg-plugin.php via
 *   ElggPlugin::getStaticConfig('routes'). Path placeholders are filled
 *   from live data (real guids / usernames). Optional params are filled
 *   when data exists and dropped otherwise; a required param we cannot
 *   fill skips that route (it cannot be crawled deterministically).
 *
 * One test method per pass (anon / auth) loops over every route and
 * aggregates failures into a single assertion. This is deliberate: a
 * @dataProvider / #[DataProvider] cannot be expressed once across the
 * 6-tier pipeline (annotations were removed in PHPUnit 12; attributes do
 * not parse on PHP 7.4 used by the Elgg 3.x/4.x tiers). A plain loop runs
 * identically on PHPUnit 9 -> 12 and PHP 7.4 -> 8.3.
 *
 * Config (env):
 *   RENDER_SMOKE_BASE  base URL of the running stack (default http://localhost)
 *   RENDER_SMOKE_USER  username for the authenticated pass (optional)
 *   RENDER_SMOKE_PASS  password for the authenticated pass (optional)
 *   When USER/PASS are absent the authenticated pass is skipped, not failed.
 *
 * Generated by elgg-migrate/bin/gen-render-smoke.sh — do not hand-edit.
 */
final class RenderSmokeTest extends IntegrationTestCase {

	private const PLUGIN_ID = 'hypewall';

	public function up() {}

	public function down() {}

	public function getPluginID(): string {
		return self::PLUGIN_ID;
	}

	public function testAllRoutesRenderAnonymously(): void {
		$routes = $this->routes();
		if (empty($routes)) {
			$this->markTestSkipped('plugin "' . self::PLUGIN_ID . '" registers no crawlable GET routes');
		}

		$failures = [];
		foreach ($routes as $name => $path) {
			$status = $this->httpStatus($path, null);
			if ($status >= 500) {
				$failures[] = "{$path} (route '{$name}') -> HTTP {$status}";
			}
		}

		$this->assertSame(
			[],
			$failures,
			"anon 5xx on " . count($failures) . " route(s):\n  " . implode("\n  ", $failures)
		);
	}

	public function testAllRoutesRenderAuthenticated(): void {
		$jar = $this->authCookie();
		if ($jar === null) {
			$this->markTestSkipped('no RENDER_SMOKE_USER/PASS set — authenticated pass skipped');
		}

		$routes = $this->routes();
		if (empty($routes)) {
			$this->markTestSkipped('plugin "' . self::PLUGIN_ID . '" registers no crawlable GET routes');
		}

		$failures = [];
		foreach ($routes as $name => $path) {
			$status = $this->httpStatus($path, $jar);
			if ($status >= 500) {
				$failures[] = "{$path} (route '{$name}') -> HTTP {$status}";
			}
		}

		$this->assertSame(
			[],
			$failures,
			"auth 5xx on " . count($failures) . " route(s):\n  " . implode("\n  ", $failures)
		);
	}

	private static function base(): string {
		return rtrim((string) (getenv('RENDER_SMOKE_BASE') ?: 'http://localhost'), '/');
	}

	/**
	 * Concrete crawlable URL path for every GET route the plugin registers.
	 *
	 * @return array<string, string> routeName => path
	 */
	private function routes(): array {
		$plugin = elgg_get_plugin_from_id(self::PLUGIN_ID);
		if (!$plugin) {
			return [];
		}

		$routes = $plugin->getStaticConfig('routes', []);
		if (empty($routes)) {
			return [];
		}

		$out = [];
		foreach ($routes as $name => $cfg) {
			$methods = (array) ($cfg['methods'] ?? ['GET']);
			if (!in_array('GET', $methods, true)) {
				continue;
			}

			$path = $cfg['path'] ?? null;
			if (!$path) {
				continue;
			}

			$filled = $this->fillParams((string) $path);
			if ($filled === null) {
				continue; // required param we could not fill from live data
			}

			$out[(string) $name] = $filled;
		}

		return $out;
	}

	/**
	 * Resolve {param} / {param?} placeholders from live data.
	 * Returns null when a REQUIRED placeholder cannot be filled.
	 */
	private function fillParams(string $path): ?string {
		return elgg_call(ELGG_IGNORE_ACCESS, function () use ($path) {
			$out = preg_replace_callback('/\{(\w+)(\?)?\}/', function (array $m): string {
				$key = $m[1];
				$optional = ($m[2] ?? '') === '?';
				$val = $this->sampleFor($key);
				if ($val === null || $val === '') {
					return $optional ? '' : "\0SKIP\0";
				}

				return (string) $val;
			}, $path);

			if (strpos((string) $out, "\0SKIP\0") !== false) {
				return null;
			}

			$out = preg_replace('#//+#', '/', (string) $out);
			$out = rtrim((string) $out, '/');

			return $out === '' ? '/' : $out;
		});
	}

	/**
	 * @return string|int|null sample value for a route placeholder, or null if none available
	 */
	private function sampleFor(string $key) {
		if (in_array($key, ['username', 'name'], true)) {
			$u = elgg_get_entities(['type' => 'user', 'limit' => 1]);

			return $u ? $u[0]->username : null;
		}

		// catch-all / id-list segments: a single empty segment is valid
		if (in_array($key, ['segments', 'any', 'path'], true)
			|| (substr($key, -1) === 's' && strpos($key, 'guid') !== false)) {
			return '';
		}

		if (strpos($key, 'guid') !== false || in_array($key, ['lc', 'id'], true)) {
			$e = elgg_get_entities(['limit' => 1, 'order_by' => 'e.guid ASC']);

			return $e ? $e[0]->guid : null;
		}

		return '1';
	}

	private function httpStatus(string $path, ?string $cookieJar): int {
		$ch = curl_init(self::base() . $path);
		curl_setopt_array($ch, [
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_FOLLOWLOCATION => false, // a gatekeeper 302 is < 500 and fine
			CURLOPT_TIMEOUT => 30,
		]);
		if ($cookieJar !== null) {
			curl_setopt($ch, CURLOPT_COOKIEFILE, $cookieJar);
		}

		curl_exec($ch);
		$code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
		curl_close($ch);

		return $code;
	}

	/**
	 * Log in once via the live action/login flow and return the cookie jar path.
	 * Returns null when no credentials are configured or login could not start.
	 */
	private function authCookie(): ?string {
		static $jar = null;
		static $tried = false;

		if ($tried) {
			return $jar;
		}

		$tried = true;

		$user = (string) (getenv('RENDER_SMOKE_USER') ?: '');
		$pass = (string) (getenv('RENDER_SMOKE_PASS') ?: '');
		if ($user === '' || $pass === '') {
			return $jar = null;
		}

		$base = self::base();
		$jar = (string) tempnam(sys_get_temp_dir(), 'rsmoke_');

		$login = $this->curlGet($base . '/login', $jar);
		if (!preg_match('/__elgg_token[^>]*value="([^"]+)"/', $login, $tok)
			|| !preg_match('/__elgg_ts[^>]*value="(\d+)"/', $login, $ts)) {
			return $jar = null;
		}

		$ch = curl_init($base . '/action/login');
		curl_setopt_array($ch, [
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_FOLLOWLOCATION => false,
			CURLOPT_POST => true,
			CURLOPT_POSTFIELDS => http_build_query([
				'username' => $user,
				'password' => $pass,
				'__elgg_token' => $tok[1],
				'__elgg_ts' => $ts[1],
			]),
			CURLOPT_COOKIEFILE => $jar,
			CURLOPT_COOKIEJAR => $jar,
			CURLOPT_TIMEOUT => 30,
		]);
		curl_exec($ch);
		curl_close($ch);

		return $jar;
	}

	private function curlGet(string $url, string $jar): string {
		$ch = curl_init($url);
		curl_setopt_array($ch, [
			CURLOPT_RETURNTRANSFER => true,
			CURLOPT_FOLLOWLOCATION => false,
			CURLOPT_COOKIEFILE => $jar,
			CURLOPT_COOKIEJAR => $jar,
			CURLOPT_TIMEOUT => 30,
		]);
		$body = (string) curl_exec($ch);
		curl_close($ch);

		return $body;
	}
}
